### ISSUE TITLE
 python  kzmonitor.py 启动错误

### ISSUE THREAD

**Issue by hzqiyongpan** [tqlihuiqi/kzmonitor#1]
python2.6

python  kzmonitor.py
Traceback (most recent call last):
  File "kzmonitor.py", line 15, in <module>
    from handler.zookeeper import ZookeeperHandler
  File "/soft/kzmonitor-master/handler/zookeeper.py", line 9, in <module>
    from lib.client import SQLite3, Zookeeper
  File "/soft/kzmonitor-master/lib/client.py", line 148
    return {p.partition: p.offsets[0] for p in tp}
                                        ^
SyntaxError: invalid syntax

python3 

 python3  kzmonitor.py
Traceback (most recent call last):
  File "kzmonitor.py", line 15, in <module>
    from handler.zookeeper import ZookeeperHandler
  File "/soft/kzmonitor-master/handler/zookeeper.py", line 10, in <module>
    from lib.config import instance
  File "/soft/kzmonitor-master/lib/config.py", line 6, in <module>
    from ConfigParser import ConfigParser
ImportError: No module named 'ConfigParser'

**Comment by tqlihuiqi** [comment]
Hi, 我的开发环境用的是Python 2.7,  python2.6 没有花括号列表推导式的语法，python 3  里面是小写的ConfigParser(configparser)

你可以暂时使用python2.7运行kzmonitor，稍后我会修复这几个问题并且支持python2.6和python3.

**Comment by hzqiyongpan** [comment]
ok,谢谢，我在试一下

**Comment by tqlihuiqi** [comment]
@hzqiyongpan， 现已支持Python3，由于2.6过旧有些语法不能用，所以项目就先不支持2.6了。
