### ISSUE TITLE
sqlite3 报错

### ISSUE THREAD

**Issue by hzqiyongpan** [tqlihuiqi/kzmonitor#2]
sqlite报错

AttributeError: 'NoneType' object has no attribute 'items'
ERROR:tornado.application:Exception in callback <functools.partial object at 0x7fc7548e6e68>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 604, in _run_callback
    ret = callback()
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 619, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/soft/kzmonitor-master/lib/writer.py", line 79, in write
    with SQLite3(os.path.join(instance.zookeeperDatadir, "zookeeper_{}.db".format(md5Name(cluster)))) as client:
  File "/soft/kzmonitor-master/lib/client.py", line 21, in __init__
    self.db = create_engine('sqlite:///'+db, connect_args={'check_same_thread': False}, strategy = 'threadlocal')
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: /usr/local/lib/python2.7/site-packages/pysqlite2/_sqlite.so: undefined symbol: sqlite3_stmt_readonly

**Comment by tqlihuiqi** [comment]
@hzqiyongpan 是否配置了zookeeper.yaml?

**Comment by hzqiyongpan** [comment]
![image](https://cloud.githubusercontent.com/assets/4659635/23116617/60dddd78-f786-11e6-9843-5aeb1e967dea.png)

配置了，数据存入不了sqlite

**Comment by hzqiyongpan** [comment]
我用的centos6.5,应该是我的机器问题,@tqlihuiqi 有计划把sqlite改成mysql吗

**Comment by tqlihuiqi** [comment]
目前用SQLite的好处就是可以安装配置方便，我这的数据一天产生<=40M，SQLite目前可以轻松查询。后面有计划支持存MySQL。
