### ISSUE TITLE
kafka 没有数据流入

### ISSUE THREAD

**Issue by boking** [tqlihuiqi/kzmonitor#4]
启动程序之后能够看到zk是有数据的，但是kafka这边一直是0，没有数据流入

**Comment by tqlihuiqi** [comment]
提供一下详细信息吧，看一下有没有报错。

**Comment by boking** [comment]
ERROR:tornado.application:Exception in callback <functools.partial object at 0x360f260>
Traceback (most recent call last):
  File "/home/rong/opbin/.venv/lib/python2.7/site-packages/tornado/ioloop.py", line 604, in _run_callback
    ret = callback()
  File "/home/rong/opbin/.venv/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/rong/opbin/.venv/lib/python2.7/site-packages/tornado/ioloop.py", line 619, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/home/rong/opbin/.venv/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/rong/opbin/.venv/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/kzmonitor/lib/writer.py", line 40, in write
    yield client.createKafkaTable(topic, partitions)
  File "/home/rong/opbin/.venv/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/rong/opbin/.venv/lib/python2.7/site-packages/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/home/rong/opbin/.venv/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/kzmonitor/lib/client.py", line 97, in createKafkaTable
    """.format(topic, ",".join([ "p{} bigint NOT NULL".format(p) for p in partitions ]))
  File "/home/rong/opbin/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2058, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/rong/opbin/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/home/rong/opbin/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/home/rong/opbin/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/rong/opbin/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/home/rong/opbin/.venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/rong/opbin/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/rong/opbin/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) near ")": syntax error [SQL: '\n                CREATE TABLE IF NOT EXISTS `MyTopic` (\n

**Comment by tqlihuiqi** [comment]
看报错像是你配置问题，确认一下kafka.yml配置文件里面配置的是否正确，Topic是否存在。

**Comment by boking** [comment]
配置是没有问题的都是正确的，
OperationalError: (sqlite3.OperationalError) near ")": syntax error [SQL: '\n                CREATE TABLE IF NOT EXISTS `onTopic` (\n                    id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    group_name VARCHAR(100) NOT NULL,\n                    category VARCHAR(8) NOT NULL,\n                    timestamp INTEGER NOT NULL,\n                    timestamp5m INTEGER NOT NULL,\n                    timestamp10m INTEGER NOT NULL,\n                    timestamp1h INTEGER NOT NULL,\n                    \n                )\n            ']

**Comment by tqlihuiqi** [comment]
这段代码在 lib/client  85 - 98行，如下：

        self.db.execute(
            """
                CREATE TABLE IF NOT EXISTS `{}` (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    group_name VARCHAR(100) NOT NULL,
                    category VARCHAR(8) NOT NULL,
                    timestamp INTEGER NOT NULL,
                    timestamp5m INTEGER NOT NULL,
                    timestamp10m INTEGER NOT NULL,
                    timestamp1h INTEGER NOT NULL,
                    {}
                )
            """.format(topic, ",".join([ "p{} bigint NOT NULL".format(p) for p in partitions ]))
        )

创建表的时候SQL是根据Topic中的Partition拼接出来的，从你的报错来看，没有拿到Topic的partition所以SQL语法是错的才会产生异常，建议检查一下kafka Topic和Partition这块的配置。
